[book]
authors = ["blackanger"]
language = "en"
multilingual = false
src = "src"
title = "Rust Coding Specification V1.0 beta"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 2

[output.html]
git-repository-url = "https://github.com/Rust-Coding-Guidelines/rust-coding-guidelines"

[output.html.fold]
enable = true
level = 0